### ISSUE TITLE
Date in Calendar wrong after choosing date

### ISSUE THREAD

**Issue by mbdHoltby** [CodyHouse/cd-date-picker-changelog#2]
Steps to duplicate

1. Pick Date
2. Date now shoes in input field
3. Click to show calendar again (or select new date)
4. Date highlighted in calendar is one date behind

ie: Pick May 1, 2020 and you'll see when clicking to open the calendar again, April 30, 2020 is highlighted.

**Comment by claudia-romano** [comment]
Hi there,
are you experiencing this issue with a specific browser? I was testing it on Chrome 81 on Mac, and I was not able to reproduce the bug. Thanks!

**Comment by mbdHoltby** [comment]
Hi Claudia,

Below is a link to a screen capture from Chrome 81 on Mac. It is also present on Windows 10 in (Chrome 81, Firefox 75, Edge 44, IE 11)

The timezone here is EDT, that might be an issue. Or that 2020 is a leap year and the code is not taking that into account?

Screen Capture
[https://drive.google.com/a/mybrotherdarryl.com/file/d/1--hpMODgyLSvtnO-5WnOXSaL_919WA18/view?usp=sharing]

Code from page is as follows (only difference from demo code is the commented out label)

`<div class="date-input js-date-input" data-date-format="y-m-d" data-date-separator="-">
                                
                                
                                <div class="date-input__wrapper">
                                    <input type="text" class="form-control width-100% date-input__text js-date-input__text" placeholder="yyyy-mm-dd" autocomplete="off" id="date-input-1">
                                    
                                    <button class="date-input__trigger js-date-input__trigger js-tab-focus" aria-label="Choose date">
                                    <svg class="icon" aria-hidden="true" viewBox="0 0 24 24"><g stroke-linecap="square" stroke-linejoin="miter" stroke-width="2" stroke="currentColor"><line x1="17" y1="4" x2="17" y2="1" fill="none" stroke-miterlimit="10"></line><line x1="7" y1="4" x2="7" y2="1" fill="none" stroke-miterlimit="10"></line><line x1="1" y1="8" x2="23" y2="8" fill="none" stroke-miterlimit="10" stroke-linecap="butt"></line><rect x="1" y="4" width="22" height="18" fill="none" stroke="currentColor" stroke-miterlimit="10"></rect></g></svg>
                                    </button>
                                </div>
                                
                                <div class="date-picker js-date-picker" role="dialog" aria-labelledby="calendar-label-1">
                                    <header class="date-picker__header">
                                    <div class="date-picker__month">
                                        <span class="date-picker__month-label js-date-picker__month-label" id="calendar-label-1"></span> 

                                        <nav>
                                        <ul class="date-picker__month-nav js-date-picker__month-nav">
                                            <li>
                                            <button class="date-picker__month-nav-btn js-date-picker__month-nav-btn js-date-picker__month-nav-btn--prev">
                                                <svg class="icon icon--xxs" viewBox="0 0 12 12"><title>Previous month</title><polyline points="8.5 11.5 2.5 6 8.5 0.5" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></polyline></svg>
                                            </button>
                                            </li>

                                            <li>
                                            <button class="date-picker__month-nav-btn js-date-picker__month-nav-btn js-date-picker__month-nav-btn--next">
                                                <svg class="icon icon--xxs" viewBox="0 0 12 12"><title>Next month</title><polyline points="3.5 0.5 9.5 6 3.5 11.5" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"></polyline></svg>
                                            </button>
                                            </li>
                                        </ul>
                                        </nav>
                                    </div>

                                    <ol class="date-picker__week">
                                        <li><div class="date-picker__day">M<span class="sr-only">onday</span></div></li>
                                        <li><div class="date-picker__day">T<span class="sr-only">uesday</span></div></li>
                                        <li><div class="date-picker__day">W<span class="sr-only">ednesday</span></div></li>
                                        <li><div class="date-picker__day">T<span class="sr-only">hursday</span></div></li>
                                        <li><div class="date-picker__day">F<span class="sr-only">riday</span></div></li>
                                        <li><div class="date-picker__day">S<span class="sr-only">aturday</span></div></li>
                                        <li><div class="date-picker__day">S<span class="sr-only">unday</span></div></li>
                                    </ol>
                                    </header>

                                    <ol class="date-picker__dates js-date-picker__dates" aria-labelledby="calendar-label-1">
                                    
                                    </ol>
                                </div>
                            </div>`

Thanks again, let me know what else I can provide.

**Comment by mbdHoltby** [comment]
Sorry the code block above dropped the opening div

`<div class="date-input js-date-input" data-date-format="y-m-d" data-date-separator="-">`

**Comment by claudia-romano** [comment]
Hi there! Thanks for the additional info. Yes the timezone was the issue. We just pushed an updated version that should fix the problem. You can get the updated js code here:
https://codyhouse.co/ds/components/app/date-picker

Let me know if you are still experiencing this. Cheers!

**Comment by mbdHoltby** [comment]
Wonderful @claudia-romano.

Thanks for the speedy correction.

It's working well now.
