### ISSUE TITLE
Selected/current day visible in every month

### ISSUE THREAD

**Issue by w3work** [CodyHouse/cd-date-picker-changelog#3]
I think there is a small bug in relation to the selected or current day in the Datepicker.

If i open the Datepicker, then the current day is selected. Correct so far. But if i click the next month, then this day is also highlighted.
This also happens, if i click for example a random day like the 20th May. Now when switching to June or July also the 20th of this month is highlighted.

It seems it depends on these lines of code:
`.date-picker__date[tabindex="0"] {
    color: var(--color-primary);`

**Comment by claudia-romano** [comment]
Thanks for the heads-up. We just pushed a fix for this issue. You can get the updated JS code form the component page:
https://codyhouse.co/ds/components/app/date-picker

Feel free to reopen this is you are still experiencing it. Cheers.
