### ISSUE TITLE
Not displayed correctly

### ISSUE THREAD

**Issue by Zerbio** [CodyHouse/cd-date-picker-changelog#4]
Hello, I have a problem with this component, it is displayed incorrectly:

![Captura](https://user-images.githubusercontent.com/13745280/104005898-0f6aa380-51a6-11eb-93f7-eef13136b9e3.PNG)

A "::marker" appears on the console, and this is not present in your example:

![Captura](https://user-images.githubusercontent.com/13745280/104006129-5f496a80-51a6-11eb-89e8-4d6fc9cc0e43.PNG)
![Imagen1](https://user-images.githubusercontent.com/13745280/104006272-8e5fdc00-51a6-11eb-87b8-42897a3f80ac.jpg)

Thank you and greetings

**Comment by sebastiano-guerriero** [comment]
Hi! Have you imported CodyFrame before the component? https://codyhouse.co/ds/get-started

**Comment by Zerbio** [comment]
Hi, yes, of course. I tried to redo it from the beginning, including CodyFrame as npm module and also without it. The problem continues.

**Comment by sebastiano-guerriero** [comment]
From the screenshot, it seems the reset global is not being imported (e.g., the dots of the list in the header are visible, but they shoudn't). I've inspected the component code and I couldn't find the ::marker. Is it possible other frameworks/custom code is creating a conflict with the component? Can you recreate the bug if, for example, you export a CodyFrame project with just this component? https://codyhouse.co/ds/export

**Comment by Zerbio** [comment]
Doing what you tell me looks right, see if I find the problem, because I don't use any other framework or external code yet. Thanks

**Comment by Zerbio** [comment]
Having found the problem, I was inside a div with the class 'text-component'.

**Comment by sebastiano-guerriero** [comment]
Good to know :)
